sudo: 'required'

language: node_js
node_js:
  - "stable"

services:
  - 'docker'

before_install:
  - './.travis/main.sh'
  - sed -i "s/localhost/$SERVER_IP/" src/util/http.js

script:
  - 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

notifications:
  email: false